#!/bin/sh
#
# @name gazebo-classic_huaqiccc
#
# @type Quadrotor Wide
#
# 基于 SDF 精确计算：机臂闭合状态 (arm_angle=0.0)
# 总质量: 1.26064 kg
# 质心位置 (SDF): X=0.1470, Y=-0.0009, Z=-0.0156
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX -0.1936
param set-default CA_ROTOR0_PY -0.2489
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR1_PX 0.2655
param set-default CA_ROTOR1_PY -0.2292
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX -0.1983
param set-default CA_ROTOR2_PY 0.2455
param set-default CA_ROTOR2_KM 0.05
param set-default CA_ROTOR3_PX 0.2614
param set-default CA_ROTOR3_PY 0.2330
param set-default CA_ROTOR3_KM -0.05

param set-default MC_PITCHRATE_K 0.5

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
